apiVersion: apps/v1
kind: Deployment
metadata:
  name: development
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx-deployment
          image: prudhviraaz14/mywebapp:mywebapp
          ports:
            - containerPort: 80
